#!/usr/bin/env python3
"""
Load FVC2004 dataset images into the MDGT Edge database.

Selects one image per subject (impression _1) from Db1_a,
resizes to 192x192, creates User + Fingerprint records.
"""
import sys
import os
import hashlib
import logging

# Add project root to path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from mdgt_edge.database.database import DatabaseManager
from mdgt_edge.database.repository import UserRepository, FingerprintRepository
from mdgt_edge.database.models import User, Fingerprint

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def load_and_resize_image(tif_path: str, target_size: tuple = (192, 192)) -> bytes:
    """Load a .tif image, convert to grayscale, resize to target, return raw bytes."""
    from PIL import Image
    img = Image.open(tif_path).convert("L")
    img = img.resize(target_size, Image.LANCZOS)
    return img.tobytes()


def compute_quality(image_bytes: bytes) -> float:
    """Compute quality score (stddev of pixel values)."""
    if not image_bytes or len(image_bytes) < 100:
        return 0.0
    avg = sum(image_bytes) / len(image_bytes)
    variance = sum((x - avg) ** 2 for x in image_bytes) / len(image_bytes)
    return variance ** 0.5


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Load FVC2004 images into MDGT Edge DB")
    parser.add_argument(
        "--fvc-dir",
        default=os.path.join(PROJECT_ROOT, "..", "FVC2004", "Dbs", "Db1_a"),
        help="Path to FVC2004 Db1_a directory",
    )
    parser.add_argument(
        "--db-path",
        default=os.path.join(PROJECT_ROOT, "data", "mdgt_edge.db"),
        help="Path to SQLite database",
    )
    parser.add_argument(
        "--num-subjects",
        type=int,
        default=100,
        help="Number of subjects to load (1-100)",
    )
    parser.add_argument(
        "--impression",
        type=int,
        default=1,
        help="Which impression to use (1-8)",
    )
    parser.add_argument(
        "--department",
        default="FVC2004",
        help="Department name for created users",
    )
    parser.add_argument(
        "--save-images-dir",
        default=os.path.join(PROJECT_ROOT, "data", "fvc2004_images"),
        help="Directory to save resized 192x192 images (for AI pipeline)",
    )
    args = parser.parse_args()

    fvc_dir = os.path.abspath(args.fvc_dir)
    if not os.path.isdir(fvc_dir):
        logger.error("FVC2004 directory not found: %s", fvc_dir)
        sys.exit(1)

    logger.info("FVC2004 dir: %s", fvc_dir)
    logger.info("Database: %s", args.db_path)
    logger.info("Loading %d subjects, impression %d", args.num_subjects, args.impression)

    # Create image output directory
    os.makedirs(args.save_images_dir, exist_ok=True)
    logger.info("Saving resized images to: %s", args.save_images_dir)

    # Init database
    db = DatabaseManager(args.db_path)
    user_repo = UserRepository(db)
    fp_repo = FingerprintRepository(db)

    created_users = 0
    created_fps = 0
    skipped = 0

    for subject_id in range(1, args.num_subjects + 1):
        filename = f"{subject_id}_{args.impression}.tif"
        filepath = os.path.join(fvc_dir, filename)

        if not os.path.exists(filepath):
            logger.warning("File not found: %s, skipping", filename)
            skipped += 1
            continue

        employee_id = f"FVC{subject_id:04d}"
        full_name = f"FVC2004 Subject {subject_id}"

        # Check if user already exists
        existing = user_repo.get_by_employee_id(employee_id)
        if existing:
            logger.info("User %s already exists (id=%d), skipping", employee_id, existing.id)
            skipped += 1
            continue

        # Load and process image
        try:
            image_bytes = load_and_resize_image(filepath)
        except Exception as e:
            logger.error("Failed to load %s: %s", filename, e)
            skipped += 1
            continue

        # Save resized image as .raw (192x192 grayscale)
        raw_path = os.path.join(args.save_images_dir, f"{employee_id}.raw")
        with open(raw_path, "wb") as f:
            f.write(image_bytes)

        quality = compute_quality(image_bytes)
        image_hash = hashlib.sha256(image_bytes).hexdigest()

        # Create user
        user = User(
            employee_id=employee_id,
            full_name=full_name,
            department=args.department,
        )
        user = user_repo.create(user)
        created_users += 1

        # Create fingerprint record
        fp = Fingerprint(
            user_id=user.id,
            finger_index=0,
            embedding_enc=None,  # Will be generated by AI pipeline later
            minutiae_enc=None,
            quality_score=min(quality, 100.0),
            image_hash=image_hash,
        )
        fp = fp_repo.create(fp)
        created_fps += 1

        logger.info(
            "  [%3d/%-3d] user_id=%d, emp=%s, quality=%.1f, hash=%s...",
            subject_id, args.num_subjects, user.id, employee_id, quality, image_hash[:12],
        )

    logger.info("=" * 60)
    logger.info("Done! Created %d users, %d fingerprints, skipped %d", created_users, created_fps, skipped)
    logger.info("Total users in DB: %d", user_repo.count())
    logger.info("Total fingerprints in DB: %d", fp_repo.count())


if __name__ == "__main__":
    main()
